// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
import "@openzeppelin/contracts/utils/cryptography/MessageHashUtils.sol";
import "./BaseJobInfo.sol";

contract JobInfo is BaseJobInfo {
    constructor(
        address _jobCreator,
        address _adminWallet,
        address _protocolWallet,
        address[] memory _rewardTokens,
        uint256[] memory _rewardAmount
    ) {
        __BaseJobInfo_init(
            _jobCreator,
            _adminWallet,
            _protocolWallet,
            _rewardTokens,
            _rewardAmount
        );
    }

    function sendRewards(
        address _user
    ) external onlyAuthorizedAccess nonReentrant {
        if (_user == address(0)) revert ZeroAddress();
        if (hasReceivedReward[_user]) revert RewardAlreadyDistributed(_user);

        hasReceivedReward[_user] = true;
        for (uint256 i = 0; i < rewardTokens.length; i++) {
            bool success = IERC20(rewardTokens[i]).transfer(
                _user,
                rewardTokensToAmount[rewardTokens[i]]
            );
            if (!success) revert TransferFailed();
        }
        totalRewardsDistributed++;
        emit RewardsSent(_user);
    }

    /**
     * @notice Allows a user to claim their reward with a signature from protocolWallet
     * @param nonce A unique bytes32 nonce generated by the backend to prevent replay attacks
     * @param signature The signature generated by protocolWallet backend
     * @dev The signature must be generated by signing a message containing:
     *      - msg.sender (claimant address)
     *      - address(this) (contract address to prevent cross-contract replay)
     *      - block.chainid (chain ID to prevent cross-chain replay)
     *      - nonce (unique random message from backend)
     * @dev The nonce will be stored to prevent reuse
     */
    function claimReward(
        bytes32 nonce,
        bytes calldata signature
    ) external nonReentrant {
        address claimant = msg.sender;

        if (hasReceivedReward[claimant])
            revert RewardAlreadyDistributed(claimant);

        // Check if nonce has already been used
        if (usedNonces[nonce]) revert NonceAlreadyUsed(nonce);

        // Create the message hash that should be signed by protocolWallet
        // Includes claimant address, contract address, chainid, and nonce for replay protection
        bytes32 messageHash = keccak256(
            abi.encodePacked(claimant, address(this), block.chainid, nonce)
        );

        // Convert to Ethereum signed message hash (EIP-191 standard)
        bytes32 ethSignedMessageHash = MessageHashUtils.toEthSignedMessageHash(
            messageHash
        );

        // Recover the signer from the signature
        address signer = ECDSA.recover(ethSignedMessageHash, signature);

        // Verify the signer is the protocolWallet
        if (signer != protocolWallet) revert InvalidSignature();

        // Mark nonce as used to prevent replay attacks
        usedNonces[nonce] = true;

        // Mark reward as distributed before transfer to prevent reentrancy
        hasReceivedReward[claimant] = true;

        // Transfer all reward tokens to the claimant
        for (uint256 i = 0; i < rewardTokens.length; i++) {
            bool success = IERC20(rewardTokens[i]).transfer(
                claimant,
                rewardTokensToAmount[rewardTokens[i]]
            );
            if (!success) revert TransferFailed();
        }

        totalRewardsDistributed++;
        emit RewardsSent(claimant);
    }

    function batchSendRewards(
        address[] calldata _users
    )
        external
        onlyAuthorizedAccess
        nonReentrant
        returns (uint256 successCount)
    {
        uint256 userCount = _users.length;

        uint256 tokenCount = rewardTokens.length;
        address[] memory tokens = new address[](tokenCount);
        uint256[] memory amounts = new uint256[](tokenCount);

        for (uint256 i = 0; i < tokenCount; i++) {
            tokens[i] = rewardTokens[i];
            amounts[i] = rewardTokensToAmount[tokens[i]];
        }

        for (uint256 i = 0; i < userCount; i++) {
            address user = _users[i];
            if (user == address(0) || hasReceivedReward[user]) {
                continue;
            }

            hasReceivedReward[user] = true;
            bool allTransfersSuccessful = true;

            for (uint256 j = 0; j < tokenCount; j++) {
                try IERC20(tokens[j]).transfer(user, amounts[j]) {} catch {
                    allTransfersSuccessful = false;
                    break;
                }
            }

            if (allTransfersSuccessful) {
                successCount++;
                totalRewardsDistributed++;
                emit RewardsSent(user);
            } else {
                hasReceivedReward[user] = false;
            }
        }

        emit BatchRewardsSent(_users, successCount);
    }

    function setRewardsAmount(
        address[] calldata _rewardTokens,
        uint256[] calldata _rewardAmounts
    ) external onlyJobCreator {
        _updateRewards(_rewardTokens, _rewardAmounts);
    }

    function withdrawToken(
        address tokenAddress,
        uint256 amount
    ) external nonReentrant onlyJobCreator validToken(tokenAddress) {
        bool success = IERC20(tokenAddress).transfer(jobCreator, amount);
        if (!success) revert TransferFailed();

        emit WithdrawalCompleted(jobCreator, amount, tokenAddress);
    }

    function changeJobStatus() external nonReentrant onlyJobCreator {
        if (!jobStatus) revert JobAlreadyDone();

        jobStatus = false;
    }

    function changeProtocolWallet(
        address _newProtocolWallet
    ) external nonReentrant onlyAdmin {
        if (_newProtocolWallet == address(0)) revert ZeroAddress();
        protocolWallet = _newProtocolWallet;
    }

    function isAReward(address tokenAddress) public view returns (bool) {
        if (rewardTokensToAmount[tokenAddress] > 0) {
            return true;
        } else {
            return false;
        }
    }

    function getRewardAmount(
        address tokenAddress
    ) public view returns (uint256) {
        return rewardTokensToAmount[tokenAddress];
    }

    function getJobInfo()
        external
        view
        returns (address, address, address, bool)
    {
        return (jobCreator, adminWallet, protocolWallet, jobStatus);
    }

    function getRewardDetails()
        external
        view
        returns (address[] memory, uint256[] memory)
    {
        uint256 l = rewardTokens.length;
        uint256[] memory rewardAmount = new uint256[](l);
        for (uint256 i = 0; i < l; i++) {
            rewardAmount[i] = rewardTokensToAmount[rewardTokens[i]];
        }
        return (rewardTokens, rewardAmount);
    }
}
